apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-java
  template:
    metadata:
      labels:
        app: ray-java
    spec:
      containers:
        - name: ray-java
          image: us-docker.pkg.dev/$PROJECT-ID/gemma/ray-java:latest
          ports:
            - containerPort: 8080
          env:
          - name: "RAY_VLLM_URL"
            value: "gemma-2b-finetuned-serve-svc.default.svc.cluster.local"
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: ray-java
#spec:
#  selector:
#    app: ray-java
#  ports:
#    - port: 80
#      targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: ray-java
spec:
  selector:
    app: ray-java
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer